## Numpy:
Numpy library is used for scientific calculation and computing.  
Supports arrays and matrices along with collection of mathematical functions to operate on these data strucures.

In [45]:
## Importing Numpy:

import numpy as np 

arr1=np.array([1,2,3,4,5])
print("Dimension of Array-1:",arr1.ndim)       ## Dimension of arr1
print("Type of Array1:",type(arr1))


Dimension of Array-1: 1
Type of Array1: <class 'numpy.ndarray'>


## Use of Reshape , N-dimension(ndim) , Arrange:


In [46]:
arr2 = arr1.reshape(1, 5)  ## Reshaped 1-row 5-columns
print(arr2)
print("Dimension of Array-2:", arr2.ndim)

arr3 = np.array([1, 2, 3, 4])
print("Array before reshaping:\n", arr3)
print("Array after reshaping:\n", arr3.reshape(2, 2))

arr4=np.arange(0,20,3)
print("Array-4:",arr4)

[[1 2 3 4 5]]
Dimension of Array-2: 2
Array before reshaping:
 [1 2 3 4]
Array after reshaping:
 [[1 2]
 [3 4]]
Array-4: [ 0  3  6  9 12 15 18]


## Creation of matrices using lib functions:

In [54]:
## Use of ones function :
print("Ones Matrix:\n",np.ones((4,4),int))


## Use of eye function :
print("Identity Matrice:\n",np.eye(5))

Ones Matrix:
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Identity Matrice:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Vectorized operations:

In [57]:
## Creation of arrays:

v1 = np.array([2, 3, 4, 5, 6])
v2 = np.array([1, 2, 3, 4, 5])

## Vectorized OPerations:

print("Sum:", v1 + v2)
print("Difference:", v1 - v2)
print("Product:", v1 * v2)
print("Quotient:", v1 / v2)
print("Modulus:", v1 % v2)

Sum: [ 3  5  7  9 11]
Difference: [1 1 1 1 1]
Product: [ 2  6 12 20 30]
Quotient: [2.         1.5        1.33333333 1.25       1.2       ]
Modulus: [0 1 1 1 1]


## Universal Operations:

In [59]:
## Creation of array:

v=np.array([2,4,6,8,10])

## Universal Operation:

print("Square root:", np.sqrt(v))
print("Exponent:", np.exp(v))       ## e^1=2.718
print("Sine:", np.sin(v))          ## input should be in radian.
print("Logrithm:", np.log(v))      

Square root: [1.41421356 2.         2.44948974 2.82842712 3.16227766]
Exponent: [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
Sine: [ 0.90929743 -0.7568025  -0.2794155   0.98935825 -0.54402111]
Logrithm: [0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]


## Array Slicing & Indexing :

In [78]:
## Creation of array :
v = np.array([
    [1, 2, 3],
    [3, 4, 5],
    [6, 7, 8], 
    [9, 10, 11]])

print(v.ndim)
print("Matix:\n",v)

## Performing Slicing :
print("Slicing row no 1:",v[1])
print("Slicing of matrix:\n",v[0:,1:])

2
Matix:
 [[ 1  2  3]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Slicing row no 1: [3 4 5]
Slicing of matrix:
 [[ 2  3]
 [ 4  5]
 [ 7  8]
 [10 11]]
